[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mybible-get"
version = "1.0.0"
dependencies = [
    "click",
    "requests",
    "peewee",
    "rich"
]

[project.scripts]
mybible-get = "mybible_get:cli"
